pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
        stage('Upload Artifact to S3') {
            steps {
                sh '''
                    WAR_FILE=/opt/homebrew/opt/tomcat/libexec/webapps/my-app.war
                    BUCKET=harsh-s3-maven-bucket1q2w3e4r
                    VERSION=$(date +%Y-%m-%d-%H-%M-%S)

                    
                    echo "Uploading $WAR_FILE to S3 bucket $BUCKET"
                    aws s3 cp $WAR_FILE s3://$BUCKET/MAVEN-artifacts/my-app.war
                '''
            }
        }
    }
}
