pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
    }
    stage('Upload Artifact to S3') {
            steps {
                sh '''
                    WAR_FILE=target/my-app.war
                    BUCKET=harsh-s3-maven-bucket1q2w3e4r
                    
                    echo "Uploading $WAR_FILE to S3 bucket $BUCKET"
                    aws s3 cp $WAR_FILE s3://$BUCKET/artifacts/my-app.war
                '''
            }
        }
}
